Add __all__ list to explicitly export symbols
airplanedev/python-sdk pull request #146
Opened 2023-08-20 15:23 UTC by freimer

Adds `__all__` list to `__init__.py` to explicitly export symbols we want as the "public interface" to the module.

2023-08-23 16:44 UTC, ameyakhare requested changes

2023-08-23 16:44 UTC, ameyakhare commented on airplane/__init__.py
> +    "auth", "display", "files", "sleep",
where are these coming from? have these not been imported in this file? if so, can you import them here explicitly?

2023-08-24 20:51 UTC, freimer commented on airplane/__init__.py
> +    "auth", "display", "files", "sleep",
See: https://docs.python.org/3/tutorial/modules.html#importing-from-a-package

`__all__` is used to explicitly list what names you want to export as the public interface of the package.  Yes, all the names are imported in the `__init__.py` file.  It's not recommended to use `from airplane import *` and I don't.  But I get errors from pyright because the "proper" type hinting is not there.  Because `__all__` is not set, pyright shows error accessing any of the functions.  See here for an example:
https://github.com/microsoft/pyright/issues/1542

There's a rather long discussion there.  If you don't use `__all__` the recommendation is to do your imports like:
from airplane import auth as auth
so that you are explicitly publishing the names.  See here for how pyright handles this:
https://github.com/microsoft/pyright/blob/main/docs/typed-libraries.md#library-interface

2023-08-31 17:12 UTC, ameyakhare commented
nice, that worked

2023-09-11 12:37 UTC, freimer commented
I just pushed a commit to the PR with Black formatter run.  I merged in your changes first, and it should be sync'd to main so all the checks should run.  Let me know if you need anything else.

2023-09-11 17:23 UTC, merged