Add sleep methods
airplanedev/python-sdk pull request #96
Opened 2023-04-11 22:33 UTC by kellymtrinh

2023-04-17 18:54 UTC, ericliuche requested changes

2023-04-17 18:54 UTC, ericliuche commented on airplane/__init__.py
> +from airplane.api.entities import PromptReviewers, Run, RunStatus, Sleep
don't think we need to expose the `Sleep` class

2023-04-17 18:54 UTC, ericliuche commented on airplane/api/client.py
> +            skipped_by=resp["skippedBy"] if hasattr(resp, "skippedBy") else None,
`hasattr` is to check if an object has an attribute, but here `resp` is a dictionary. you can do `resp.get("skippedAt")` which will return `None` if the key isn't in the dictionary

2023-04-17 18:54 UTC, ericliuche commented on airplane/sleep.py
> +    if duration is None or duration == "":
this is just `if not duration`

2023-04-17 18:54 UTC, ericliuche commented on airplane/sleep.py
> +    milliseconds = 0
unnecessary declaration

2023-04-17 18:54 UTC, ericliuche commented on airplane/sleep.py
> +def sleep(duration: str) -> None:
hmm what do you think about `sleep` only / also accepting an integer to match python's native `time.sleep`? in the js-sdk i also see that we use a third part package for parsing the times which i think we should also do here if we want to accept a string.

2023-04-17 19:05 UTC, kellymtrinh commented on airplane/sleep.py
> +def sleep(duration: str) -> None:
I think having it so that customers can write "12s" or "12min" might be nice? What did you have in mind if we're accepting a string?

2023-04-24 21:10 UTC, kellymtrinh commented
Retested using this version that uses `pytimeparse2` and verified it works.

2023-04-26 20:01 UTC, ericliuche approved these changes

2023-04-26 20:01 UTC, ericliuche commented on airplane/sleep.py
> +    time.sleep(milliseconds / 1000)
minor, but since `pytimeparse2.parse` returns in seconds, and if we allow duration to be a float in seconds, we could just do `seconds = parse_time(duration)` and then 

```
    if seconds < 1:
        raise ValueError("sleep duration must be at least 1 second")
    start_time = datetime.datetime.utcnow()
    end_time = calculate_end_time_iso(start_time, seconds)
    api_client_from_env().create_sleep(seconds * 1000, end_time)
    time.sleep(seconds)
```

up to you!

2023-04-27 19:40 UTC, merged